version: 2

sources:
  - name: instawork-dw-backend
    schema: iw_backend_db
    tables:
      - name: backend_userprofile
      - name: backend_workerlevellog
      - name: backend_workerlog
      - name: backend_shift
      - name: backend_shiftgroup
      - name: backend_gigtemplate
      - name: backend_workexperience
      - name: backend_workerquizscore
      - name: business
      - name: places_place
      - name: positions_position
  - name: instawork-dw-amplitude
    schema: amplitude_beta
    tables:
      - name: schema_173137-events_173137

models:
  - name: pro_profile_features
    description: "Profile features for pros"
    columns:
      - name: ID_worker_id
        description: "The worker_id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_worker_id
  - name: pro_shift_pairing_features
    description: "Business features"
    columns:
      - name: ID_business_id
        description: "The business_id for the table"
        tests:
          - not_null
  - name: pro_amplitude_session_features
    description: "Amplitude sessions for pros"
    columns:
      - name: ID_worker_id
        description: "The worker_id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_worker_id
  - name: pro_worker_experience_features
    description: "Work experience for pros"
    columns:
      - name: ID_worker_id
        description: "The worker_id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_worker_id
  - name: pro_quiz_aggregate_features
    description: "Quiz scores for pros"
    columns:
      - name: ID_worker_id
        description: "The worker_id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_worker_id
  - name: pro_future_features
    description: "Counter features encapsulating pro related events for shifts in the future"
    columns:
      - name: ID_worker_id
        description: "The worker_id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_worker_id
  - name: pro_history_features
    description: "Counter features encapsulating pro related events for shifts in the past"
    columns:
      - name: ID_worker_id
        description: "The worker_id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_worker_id
  - name: pro_business_future_features
    description: "Counter features encapsulating pro and business related events for shifts in the future"
    columns:
      - name: ID_worker_id
        description: "The worker_id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_worker_id
            - ID_business_id
  - name: pro_business_history_features
    description: "Counter features encapsulating pro and business related events for shifts in the past"
    columns:
      - name: ID_worker_id
        description: "The worker_id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_worker_id
            - ID_business_id
  - name: business_features
    description: "Business related features"
    columns:
      - name: ID_business_id
        description: "The business id for the table"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ds
            - ID_business_id
